update ruble sign
dart-lang/intl pull request #263
Opened 2020-02-27 09:38 UTC by sanekyy

Hello. I have update ruble sign to official. 

About ruble sign [here](https://en.wikipedia.org/wiki/Ruble_sign).

New sign: ₽ ( U+20BD )

Related issue: #262

2020-09-22 12:14 UTC, marinat commented
Please, repeat review of pr.

2020-10-02 18:46 UTC, kevmoo commented
@sanekyy – please fix tests!

Also: this should change should be mentioned in the changelog.

CC @davidmorgan

2020-10-05 17:58 UTC, sanekyy commented
@kevmoo fixed.

2021-03-09 17:28 UTC, sanekyy commented
@kevmoo friendly ping

any news?

2021-03-09 21:22 UTC, srawlins commented
The owners file for the intl package internally lists two Googlers.

2021-05-10 16:23 UTC, otopba commented
Any updates? =/

1 year has already passed

2021-09-12 18:45 UTC, sanekyy commented
Hello @kevmoo @davidmorgan @srawlins 

Can you help to merge this PR?

one and half year waiting:(

2022-12-09 13:37 UTC, mosuem commented
This needs merge conflict resolution, but LGTM apart from that, as we don't get the currency symbols from CLDR.

2022-12-19 09:12 UTC, mosuem requested changes

2022-12-19 09:12 UTC, mosuem commented on test/number_format_compact_test.dart
> +import 'package:test/test.dart';
Why re-import the package?

2022-12-19 09:12 UTC, mosuem commented on AUTHORS
> +Aleksandr Yurkovskiy sanekyy@gmail.com
Do we actually use the `AUTHORS` file like this @devoncarew ?

2022-12-20 07:01 UTC, mosuem approved these changes

2022-12-20 08:41 UTC, merged